### ISSUE TITLE
Damaged xlsx

### ISSUE THREAD

**Issue by joaconigro** [Alexander-r/QtXlsxWriter#2]
Hi @Alexander-r, thank you for your library (and also thanks to @dbzhang800). 

I've been using your fork to write a xlsx file within my code. But when I try to open all files I saved with Excel (win/mac) says that file is damaged. If I open the same file with LibreOffice, the file opens just fine. 

Do you know how to solve it?
Thank you so much!

Here is one example:
[2.xlsx](https://github.com/Alexander-r/QtXlsxWriter/files/980251/2.xlsx)

**Comment by Alexander-r** [comment]
Thank you for reporting this.
I can't check it in Excel right now. Will look into it when I have an opportunity.
I've tried generating the file with library and then re-saving it with LibreOffice and compare the results, but I did not see anything that might help solve this issue. Will have to do more tests with Excel to see what it expects to be in the file.

**Comment by joaconigro** [comment]
Hi again, thanks for the quick response! 
Here are two xlsx files. The "1.xlsx" was generated with QtXlsxWriter, opens fine on LibreOffice, but it reports as damaged on Excel. The "2.xlsx" is the same 1.xlsx opened with LibreOffice and re-saved without any modification, and now Excel can open this file without a problem.

Greetings
[2.xlsx](https://github.com/Alexander-r/QtXlsxWriter/files/981673/2.xlsx)
[1.xlsx](https://github.com/Alexander-r/QtXlsxWriter/files/981674/1.xlsx)

**Comment by Alexander-r** [comment]
Finally had time to look into this problem.
It seams Excel expects "pageMargins" element in worksheet to be strictly before "pageSetup" element although they are both leaf elements of "worksheet".
Also looking at the code "pageSetup" element might have been written a second time in document if any parameters were different from defaults.

Please check if cf609ea7e3c3ff4fb66f5b2bdcc540a1bfd913f1 commit fixes this issue.
With this fix on my tests (with rather simple file...) Excel opens the document without error.

**Comment by joaconigro** [comment]
Hi Alexander, thanks for your time!
I've tried and works perfectly! I have a work trip tomorrow, but next week I will do more tests.

Thanks again!

**Comment by joaconigro** [comment]
Well, I been testing a lot of possible combinations of Excel files on my app, on differents platforms (Windows, Mac and Linux) and works perfectlly. 

I think this issue can be closed now. 

Thanks again for your work, Alexander. Regards
